
SELECT 
	--DISTINCT cur_name, ',MAX(CASE cur_name WHEN ''' || cur_name || ''' THEN cur_rate ELSE null END) AS ' || cur_name 
	 -- cur_uid 
	 --,cur_time 
	 --,cur_name 
	 --,cur_rate 
	 
	 cur_time 
	,MAX(CASE cur_name WHEN 'AED' THEN cur_rate ELSE null END) AS AED
	,MAX(CASE cur_name WHEN 'AFN' THEN cur_rate ELSE null END) AS AFN
	,MAX(CASE cur_name WHEN 'ALL' THEN cur_rate ELSE null END) AS ALL
	,MAX(CASE cur_name WHEN 'AMD' THEN cur_rate ELSE null END) AS AMD
	,MAX(CASE cur_name WHEN 'ANG' THEN cur_rate ELSE null END) AS ANG
	,MAX(CASE cur_name WHEN 'AOA' THEN cur_rate ELSE null END) AS AOA
	,MAX(CASE cur_name WHEN 'ARS' THEN cur_rate ELSE null END) AS ARS
	,MAX(CASE cur_name WHEN 'AUD' THEN cur_rate ELSE null END) AS AUD
	,MAX(CASE cur_name WHEN 'AWG' THEN cur_rate ELSE null END) AS AWG
	,MAX(CASE cur_name WHEN 'AZN' THEN cur_rate ELSE null END) AS AZN
	,MAX(CASE cur_name WHEN 'BAM' THEN cur_rate ELSE null END) AS BAM
	,MAX(CASE cur_name WHEN 'BBD' THEN cur_rate ELSE null END) AS BBD
	,MAX(CASE cur_name WHEN 'BDT' THEN cur_rate ELSE null END) AS BDT
	,MAX(CASE cur_name WHEN 'BGN' THEN cur_rate ELSE null END) AS BGN
	,MAX(CASE cur_name WHEN 'BHD' THEN cur_rate ELSE null END) AS BHD
	,MAX(CASE cur_name WHEN 'BIF' THEN cur_rate ELSE null END) AS BIF
	,MAX(CASE cur_name WHEN 'BMD' THEN cur_rate ELSE null END) AS BMD
	,MAX(CASE cur_name WHEN 'BND' THEN cur_rate ELSE null END) AS BND
	,MAX(CASE cur_name WHEN 'BOB' THEN cur_rate ELSE null END) AS BOB
	,MAX(CASE cur_name WHEN 'BRL' THEN cur_rate ELSE null END) AS BRL
	,MAX(CASE cur_name WHEN 'BSD' THEN cur_rate ELSE null END) AS BSD
	,MAX(CASE cur_name WHEN 'BTC' THEN cur_rate ELSE null END) AS BTC
	,MAX(CASE cur_name WHEN 'BTN' THEN cur_rate ELSE null END) AS BTN
	,MAX(CASE cur_name WHEN 'BWP' THEN cur_rate ELSE null END) AS BWP
	,MAX(CASE cur_name WHEN 'BYR' THEN cur_rate ELSE null END) AS BYR
	,MAX(CASE cur_name WHEN 'BZD' THEN cur_rate ELSE null END) AS BZD
	,MAX(CASE cur_name WHEN 'CAD' THEN cur_rate ELSE null END) AS CAD
	,MAX(CASE cur_name WHEN 'CDF' THEN cur_rate ELSE null END) AS CDF
	,MAX(CASE cur_name WHEN 'CHF' THEN cur_rate ELSE null END) AS CHF
	,MAX(CASE cur_name WHEN 'CLF' THEN cur_rate ELSE null END) AS CLF
	,MAX(CASE cur_name WHEN 'CLP' THEN cur_rate ELSE null END) AS CLP
	,MAX(CASE cur_name WHEN 'CNY' THEN cur_rate ELSE null END) AS CNY
	,MAX(CASE cur_name WHEN 'COP' THEN cur_rate ELSE null END) AS COP
	,MAX(CASE cur_name WHEN 'CRC' THEN cur_rate ELSE null END) AS CRC
	,MAX(CASE cur_name WHEN 'CUC' THEN cur_rate ELSE null END) AS CUC
	,MAX(CASE cur_name WHEN 'CUP' THEN cur_rate ELSE null END) AS CUP
	,MAX(CASE cur_name WHEN 'CVE' THEN cur_rate ELSE null END) AS CVE
	,MAX(CASE cur_name WHEN 'CZK' THEN cur_rate ELSE null END) AS CZK
	,MAX(CASE cur_name WHEN 'DJF' THEN cur_rate ELSE null END) AS DJF
	,MAX(CASE cur_name WHEN 'DKK' THEN cur_rate ELSE null END) AS DKK
	,MAX(CASE cur_name WHEN 'DOP' THEN cur_rate ELSE null END) AS DOP
	,MAX(CASE cur_name WHEN 'DZD' THEN cur_rate ELSE null END) AS DZD
	,MAX(CASE cur_name WHEN 'EEK' THEN cur_rate ELSE null END) AS EEK
	,MAX(CASE cur_name WHEN 'EGP' THEN cur_rate ELSE null END) AS EGP
	,MAX(CASE cur_name WHEN 'ERN' THEN cur_rate ELSE null END) AS ERN
	,MAX(CASE cur_name WHEN 'ETB' THEN cur_rate ELSE null END) AS ETB
	,MAX(CASE cur_name WHEN 'EUR' THEN cur_rate ELSE null END) AS EUR
	,MAX(CASE cur_name WHEN 'FJD' THEN cur_rate ELSE null END) AS FJD
	,MAX(CASE cur_name WHEN 'FKP' THEN cur_rate ELSE null END) AS FKP
	,MAX(CASE cur_name WHEN 'GBP' THEN cur_rate ELSE null END) AS GBP
	,MAX(CASE cur_name WHEN 'GEL' THEN cur_rate ELSE null END) AS GEL
	,MAX(CASE cur_name WHEN 'GGP' THEN cur_rate ELSE null END) AS GGP
	,MAX(CASE cur_name WHEN 'GHS' THEN cur_rate ELSE null END) AS GHS
	,MAX(CASE cur_name WHEN 'GIP' THEN cur_rate ELSE null END) AS GIP
	,MAX(CASE cur_name WHEN 'GMD' THEN cur_rate ELSE null END) AS GMD
	,MAX(CASE cur_name WHEN 'GNF' THEN cur_rate ELSE null END) AS GNF
	,MAX(CASE cur_name WHEN 'GTQ' THEN cur_rate ELSE null END) AS GTQ
	,MAX(CASE cur_name WHEN 'GYD' THEN cur_rate ELSE null END) AS GYD
	,MAX(CASE cur_name WHEN 'HKD' THEN cur_rate ELSE null END) AS HKD
	,MAX(CASE cur_name WHEN 'HNL' THEN cur_rate ELSE null END) AS HNL
	,MAX(CASE cur_name WHEN 'HRK' THEN cur_rate ELSE null END) AS HRK
	,MAX(CASE cur_name WHEN 'HTG' THEN cur_rate ELSE null END) AS HTG
	,MAX(CASE cur_name WHEN 'HUF' THEN cur_rate ELSE null END) AS HUF
	,MAX(CASE cur_name WHEN 'IDR' THEN cur_rate ELSE null END) AS IDR
	,MAX(CASE cur_name WHEN 'ILS' THEN cur_rate ELSE null END) AS ILS
	,MAX(CASE cur_name WHEN 'IMP' THEN cur_rate ELSE null END) AS IMP
	,MAX(CASE cur_name WHEN 'INR' THEN cur_rate ELSE null END) AS INR
	,MAX(CASE cur_name WHEN 'IQD' THEN cur_rate ELSE null END) AS IQD
	,MAX(CASE cur_name WHEN 'IRR' THEN cur_rate ELSE null END) AS IRR
	,MAX(CASE cur_name WHEN 'ISK' THEN cur_rate ELSE null END) AS ISK
	,MAX(CASE cur_name WHEN 'JEP' THEN cur_rate ELSE null END) AS JEP
	,MAX(CASE cur_name WHEN 'JMD' THEN cur_rate ELSE null END) AS JMD
	,MAX(CASE cur_name WHEN 'JOD' THEN cur_rate ELSE null END) AS JOD
	,MAX(CASE cur_name WHEN 'JPY' THEN cur_rate ELSE null END) AS JPY
	,MAX(CASE cur_name WHEN 'KES' THEN cur_rate ELSE null END) AS KES
	,MAX(CASE cur_name WHEN 'KGS' THEN cur_rate ELSE null END) AS KGS
	,MAX(CASE cur_name WHEN 'KHR' THEN cur_rate ELSE null END) AS KHR
	,MAX(CASE cur_name WHEN 'KMF' THEN cur_rate ELSE null END) AS KMF
	,MAX(CASE cur_name WHEN 'KPW' THEN cur_rate ELSE null END) AS KPW
	,MAX(CASE cur_name WHEN 'KRW' THEN cur_rate ELSE null END) AS KRW
	,MAX(CASE cur_name WHEN 'KWD' THEN cur_rate ELSE null END) AS KWD
	,MAX(CASE cur_name WHEN 'KYD' THEN cur_rate ELSE null END) AS KYD
	,MAX(CASE cur_name WHEN 'KZT' THEN cur_rate ELSE null END) AS KZT
	,MAX(CASE cur_name WHEN 'LAK' THEN cur_rate ELSE null END) AS LAK
	,MAX(CASE cur_name WHEN 'LBP' THEN cur_rate ELSE null END) AS LBP
	,MAX(CASE cur_name WHEN 'LKR' THEN cur_rate ELSE null END) AS LKR
	,MAX(CASE cur_name WHEN 'LRD' THEN cur_rate ELSE null END) AS LRD
	,MAX(CASE cur_name WHEN 'LSL' THEN cur_rate ELSE null END) AS LSL
	,MAX(CASE cur_name WHEN 'LTL' THEN cur_rate ELSE null END) AS LTL
	,MAX(CASE cur_name WHEN 'LVL' THEN cur_rate ELSE null END) AS LVL
	,MAX(CASE cur_name WHEN 'LYD' THEN cur_rate ELSE null END) AS LYD
	,MAX(CASE cur_name WHEN 'MAD' THEN cur_rate ELSE null END) AS MAD
	,MAX(CASE cur_name WHEN 'MDL' THEN cur_rate ELSE null END) AS MDL
	,MAX(CASE cur_name WHEN 'MGA' THEN cur_rate ELSE null END) AS MGA
	,MAX(CASE cur_name WHEN 'MKD' THEN cur_rate ELSE null END) AS MKD
	,MAX(CASE cur_name WHEN 'MMK' THEN cur_rate ELSE null END) AS MMK
	,MAX(CASE cur_name WHEN 'MNT' THEN cur_rate ELSE null END) AS MNT
	,MAX(CASE cur_name WHEN 'MOP' THEN cur_rate ELSE null END) AS MOP
	,MAX(CASE cur_name WHEN 'MRO' THEN cur_rate ELSE null END) AS MRO
	,MAX(CASE cur_name WHEN 'MTL' THEN cur_rate ELSE null END) AS MTL
	,MAX(CASE cur_name WHEN 'MUR' THEN cur_rate ELSE null END) AS MUR
	,MAX(CASE cur_name WHEN 'MVR' THEN cur_rate ELSE null END) AS MVR
	,MAX(CASE cur_name WHEN 'MWK' THEN cur_rate ELSE null END) AS MWK
	,MAX(CASE cur_name WHEN 'MXN' THEN cur_rate ELSE null END) AS MXN
	,MAX(CASE cur_name WHEN 'MYR' THEN cur_rate ELSE null END) AS MYR
	,MAX(CASE cur_name WHEN 'MZN' THEN cur_rate ELSE null END) AS MZN
	,MAX(CASE cur_name WHEN 'NAD' THEN cur_rate ELSE null END) AS NAD
	,MAX(CASE cur_name WHEN 'NGN' THEN cur_rate ELSE null END) AS NGN
	,MAX(CASE cur_name WHEN 'NIO' THEN cur_rate ELSE null END) AS NIO
	,MAX(CASE cur_name WHEN 'NOK' THEN cur_rate ELSE null END) AS NOK
	,MAX(CASE cur_name WHEN 'NPR' THEN cur_rate ELSE null END) AS NPR
	,MAX(CASE cur_name WHEN 'NZD' THEN cur_rate ELSE null END) AS NZD
	,MAX(CASE cur_name WHEN 'OMR' THEN cur_rate ELSE null END) AS OMR
	,MAX(CASE cur_name WHEN 'PAB' THEN cur_rate ELSE null END) AS PAB
	,MAX(CASE cur_name WHEN 'PEN' THEN cur_rate ELSE null END) AS PEN
	,MAX(CASE cur_name WHEN 'PGK' THEN cur_rate ELSE null END) AS PGK
	,MAX(CASE cur_name WHEN 'PHP' THEN cur_rate ELSE null END) AS PHP
	,MAX(CASE cur_name WHEN 'PKR' THEN cur_rate ELSE null END) AS PKR
	,MAX(CASE cur_name WHEN 'PLN' THEN cur_rate ELSE null END) AS PLN
	,MAX(CASE cur_name WHEN 'PYG' THEN cur_rate ELSE null END) AS PYG
	,MAX(CASE cur_name WHEN 'QAR' THEN cur_rate ELSE null END) AS QAR
	,MAX(CASE cur_name WHEN 'RON' THEN cur_rate ELSE null END) AS RON
	,MAX(CASE cur_name WHEN 'RSD' THEN cur_rate ELSE null END) AS RSD
	,MAX(CASE cur_name WHEN 'RUB' THEN cur_rate ELSE null END) AS RUB
	,MAX(CASE cur_name WHEN 'RWF' THEN cur_rate ELSE null END) AS RWF
	,MAX(CASE cur_name WHEN 'SAR' THEN cur_rate ELSE null END) AS SAR
	,MAX(CASE cur_name WHEN 'SBD' THEN cur_rate ELSE null END) AS SBD
	,MAX(CASE cur_name WHEN 'SCR' THEN cur_rate ELSE null END) AS SCR
	,MAX(CASE cur_name WHEN 'SDG' THEN cur_rate ELSE null END) AS SDG
	,MAX(CASE cur_name WHEN 'SEK' THEN cur_rate ELSE null END) AS SEK
	,MAX(CASE cur_name WHEN 'SGD' THEN cur_rate ELSE null END) AS SGD
	,MAX(CASE cur_name WHEN 'SHP' THEN cur_rate ELSE null END) AS SHP
	,MAX(CASE cur_name WHEN 'SLL' THEN cur_rate ELSE null END) AS SLL
	,MAX(CASE cur_name WHEN 'SOS' THEN cur_rate ELSE null END) AS SOS
	,MAX(CASE cur_name WHEN 'SRD' THEN cur_rate ELSE null END) AS SRD
	,MAX(CASE cur_name WHEN 'STD' THEN cur_rate ELSE null END) AS STD
	,MAX(CASE cur_name WHEN 'SVC' THEN cur_rate ELSE null END) AS SVC
	,MAX(CASE cur_name WHEN 'SYP' THEN cur_rate ELSE null END) AS SYP
	,MAX(CASE cur_name WHEN 'SZL' THEN cur_rate ELSE null END) AS SZL
	,MAX(CASE cur_name WHEN 'THB' THEN cur_rate ELSE null END) AS THB
	,MAX(CASE cur_name WHEN 'TJS' THEN cur_rate ELSE null END) AS TJS
	,MAX(CASE cur_name WHEN 'TMT' THEN cur_rate ELSE null END) AS TMT
	,MAX(CASE cur_name WHEN 'TND' THEN cur_rate ELSE null END) AS TND
	,MAX(CASE cur_name WHEN 'TOP' THEN cur_rate ELSE null END) AS TOP
	,MAX(CASE cur_name WHEN 'TRY' THEN cur_rate ELSE null END) AS TRY
	,MAX(CASE cur_name WHEN 'TTD' THEN cur_rate ELSE null END) AS TTD
	,MAX(CASE cur_name WHEN 'TWD' THEN cur_rate ELSE null END) AS TWD
	,MAX(CASE cur_name WHEN 'TZS' THEN cur_rate ELSE null END) AS TZS
	,MAX(CASE cur_name WHEN 'UAH' THEN cur_rate ELSE null END) AS UAH
	,MAX(CASE cur_name WHEN 'UGX' THEN cur_rate ELSE null END) AS UGX
	,MAX(CASE cur_name WHEN 'USD' THEN cur_rate ELSE null END) AS USD
	,MAX(CASE cur_name WHEN 'UYU' THEN cur_rate ELSE null END) AS UYU
	,MAX(CASE cur_name WHEN 'UZS' THEN cur_rate ELSE null END) AS UZS
	,MAX(CASE cur_name WHEN 'VEF' THEN cur_rate ELSE null END) AS VEF
	,MAX(CASE cur_name WHEN 'VND' THEN cur_rate ELSE null END) AS VND
	,MAX(CASE cur_name WHEN 'VUV' THEN cur_rate ELSE null END) AS VUV
	,MAX(CASE cur_name WHEN 'WST' THEN cur_rate ELSE null END) AS WST
	,MAX(CASE cur_name WHEN 'XAF' THEN cur_rate ELSE null END) AS XAF
	,MAX(CASE cur_name WHEN 'XAG' THEN cur_rate ELSE null END) AS XAG
	,MAX(CASE cur_name WHEN 'XAU' THEN cur_rate ELSE null END) AS XAU
	,MAX(CASE cur_name WHEN 'XCD' THEN cur_rate ELSE null END) AS XCD
	,MAX(CASE cur_name WHEN 'XDR' THEN cur_rate ELSE null END) AS XDR
	,MAX(CASE cur_name WHEN 'XOF' THEN cur_rate ELSE null END) AS XOF
	,MAX(CASE cur_name WHEN 'XPD' THEN cur_rate ELSE null END) AS XPD
	,MAX(CASE cur_name WHEN 'XPF' THEN cur_rate ELSE null END) AS XPF
	,MAX(CASE cur_name WHEN 'XPT' THEN cur_rate ELSE null END) AS XPT
	,MAX(CASE cur_name WHEN 'YER' THEN cur_rate ELSE null END) AS YER
	,MAX(CASE cur_name WHEN 'ZAR' THEN cur_rate ELSE null END) AS ZAR
	,MAX(CASE cur_name WHEN 'ZMK' THEN cur_rate ELSE null END) AS ZMK
	,MAX(CASE cur_name WHEN 'ZMW' THEN cur_rate ELSE null END) AS ZMW
	,MAX(CASE cur_name WHEN 'ZWL' THEN cur_rate ELSE null END) AS ZWL

FROM t_map_currency_rate
ORDER BY cur_time 
